---
title: "Data Import Practice"
format:
  html:
    code-fold: true
    code-summary: "the code's hiding spot"
editor: visual
---

```{r}
#| message: false
library(tidyverse)
library(readxl)
library(here)
```

## Step 1: Read in the dataset `ages.csv`.

```{r}
#| message: false
# Code to read in the ages.csv data goes here! 
ages_data <- read_csv(here::here("supporting_artifacts",
                                 "learning_targets",
                                 "Preview Activity 7",
                                 "ages.csv"))

```

## Step 2: Read in the dataset `ages_tab.txt`

```{r}
#| message: false
# Code to read in the ages_tab.txt data goes here! 
ages_tab_data <- read_table(here::here("supporting_artifacts",
                                       "Preview Activity 7",
                                       "ages_tab.txt"))

```

## Step 3: Read in the dataset `ages_mystery.txt`

```{r}
#| message: false
# Code to read in the ages_mystery.txt data goes here! 
ages_mystery_data <- read_delim(here::here("supporting_artifacts",
                      "Preview Activity 7",
                      "ages_mystery.txt"), delim = "|")

```

## Step 4: Read in the dataset `ages.xlsx`

```{r}
# Code to read in the ages.xlsx data goes here! 
ages_xlsx_data <- read_excel(here::here("supporting_artifacts",
                                        "Preview Activity 7",
                                        "ages.xlsx"))

```

## Step 5: Both `read.csv` and `read.table` have an optional argument called `stringsAsFactors`. Figure out what this does.

```{r}
stringsAsFactors_csv <- read.csv(here::here("supporting_artifacts",
                                            "Preview Activity 7",
                                            "ages.csv"),
                                 stringsAsFactors = TRUE)
#name observations are changed to data type Factor instead of strings

```

## Step 6: Find a way to use `read_csv()` to read `ages.csv` with the variable "Name" as a factor and "Age" as a character.

```{r}
# Code to read in the ages.csv with "Name" as a factor and "Age" as a character goes here! 

step_6 <- read_csv(here::here("supporting_artifacts",
                                            "Preview Activity 7",
                                            "ages.csv"),
                   col_types = cols(
                     Name = col_factor(),
                     Age = col_character()
                   ))
```

------------------------------------------------------------------------
