---
title: "Lightning Round Essays"
format:
  html:
    self-contained: true
    theme: lux
author: "Hannah Pawig"
date: "12/3/22"
editor: visual
---

1.  If Anagha doesn't earn an A in this class, then no one should because from what I've seen, she has put much of her effort into each of the labs and assignments, asking questions in the class discord, revising all her assignments that needed revisions, and going to office hours almost every week sometimes even just for clarification on things.

2.  The hardest part of this class for me was summarizing numerical variables over several groups when the data is fairly large, such as in Lab 4, because it took lots of time for me to understand the tools needed and their order in my pipeline to create the desired summary output in a data frame format.

3.  The easiest part of the class for me was consistently making my documents look nice and writing documented and tidy code at all times, because I like when things are organized anyway and so that came to me naturally.

4.  The part that surprised me the most was making beautiful graphs by writing code *and* the many available customizable options you can include to improve them; I didn't know that stuff like that could be done in R/Rstudio before this class.

5.  If you're stuck on something please go to your classmates or the professor, because collaboration and sharing ideas can really help you and others.
