---
title: "Practice Activity 9.2 Simulation"
author: "Hannah Pawig"
format: 
  html:
editor: visual
---

# Warm Up

## 1. 95th percentile for trumpet weight

```{r}
qunif(p = 0.95, min = 1.5, max = 3.5)
```

## 2. 10th percentile for trombone weight

```{r}
qnorm(p = .1, mean = 4.6, sd = 0.8)
```

## 3. About what percent of trombones do you expect to be more than 5 pounds?

```{r}
1-pnorm(q = 5, mean = 4.6, sd = 0.8)
```

## 4. About what percent of reed instruments do you expect to be more than 5 pounds?

```{r}
1-pchisq(q = 5, df = 4)
```

## 5. Simulate 100 random trombone weights. How many of them were below 4 pounds?

```{r}
set.seed(1)
weights <- rnorm(100, mean = 4.6, sd = 0.8)
sum(weights<4)
```

# Catching a Con

## 6.

```{r}
music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n = n_reed, df = 4)
  total_weight <- sum(trombones) + sum(cornets) + sum(reeds)
  
  return(total_weight)
  
}

set.seed(1957)

my_weights <- rerun(.n = 1000, 
                    music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)
                    ) |> 
  flatten_dbl()

sum(my_weights < 4532)

```
